const ROLES = {
  USER: 'user',
  WORKER: 'worker',
  ADMIN: 'admin'
};

const COMPLAINT_STATUS = {
  PENDING: 'Pending',
  UNDER_REVIEW: 'Under Review',
  ASSIGNED: 'Assigned',
  ACCEPTED: 'Accepted',
  IN_PROGRESS: 'In Progress',
  RESOLVED: 'Resolved',
  REOPENED: 'Reopened',
  CLOSED: 'Closed',
  REJECTED: 'Rejected'
};

const COMPLAINT_PRIORITY = {
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
  CRITICAL: 'Critical'
};

const USER_STATUS = {
  ACTIVE: 'active',
  SUSPENDED: 'suspended'
};

const WORKER_STATUS = {
  AVAILABLE: 'available',
  BUSY: 'busy',
  ON_LEAVE: 'on_leave'
};

const NOTIFICATION_TYPES = {
  COMPLAINT_CREATED: 'COMPLAINT_CREATED',
  COMPLAINT_ASSIGNED: 'COMPLAINT_ASSIGNED',
  WORKER_ACCEPTED: 'WORKER_ACCEPTED',
  WORKER_REJECTED: 'WORKER_REJECTED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  RESOLUTION_SUBMITTED: 'RESOLUTION_SUBMITTED',
  COMPLAINT_CLOSED: 'COMPLAINT_CLOSED',
  COMPLAINT_REOPENED: 'COMPLAINT_REOPENED',
  SYSTEM_ALERT: 'SYSTEM_ALERT'
};

module.exports = {
  ROLES,
  COMPLAINT_STATUS,
  COMPLAINT_PRIORITY,
  USER_STATUS,
  WORKER_STATUS,
  NOTIFICATION_TYPES
};
